import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../component/Layout";
import React from "react";
class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  SelectNum = (e) => {
    var cardNum = e.currentTarget.value;
    router.push({
      pathname: "/Spread",
      query: {
        choose: cardNum,
      },
    });
  };

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          
        </Layout>
      </div>
    );
  }
}
export default Home;
